name: single_player_app
description: LitGame single-player.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  flutter_markdown: ^0.6.9
  shared_preferences: ^2.0.11
  catcher: ^0.6.9
  flip_card: ^0.5.0
  swipeable_card_stack:
    #path: ../../cta-flutter-tinder-card-animation
    git: https://github.com/ASGAlex/cta-flutter-tinder-card-animation.git
  litgame_server:
    git: https://github.com/litgame/rest-server.git
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  flutter_swiper_null_safety: ^1.0.2
  path_provider: ^2.0.8
  connectivity_plus: ^2.1.0
  flutter_spinbox: ^0.8.0
  kplayer: ^0.1.11
  flutter_vibrate: ^1.3.0


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  msix: ^2.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logo_ios.png"
  # adaptive_icon_background: ffffff
  #adaptive_icon_foreground: 00C0FF

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/
    - assets/images/magic/


msix_config:
  display_name: LitGame
  publisher: CN=C727FA65-B02F-4784-9B5B-9F54BC6D46CB
  publisher_display_name: DigitalWand
  identity_name: DigitalWand.LitGame
  package_family_name: DigitalWand.LitGame_ss7229ge0wg1m
  msix_version: 1.0.0.0
  logo_path: C:\Users\asgal\Documents\Projects\litgame\single_player_app\assets\images\logo.png
  start_menu_icon_path: C:\Users\asgal\Documents\Projects\litgame\single_player_app\assets\images\logo.png
  tile_icon_path: C:\Users\asgal\Documents\Projects\litgame\single_player_app\assets\images\logo.png
  vs_generated_images_folder_path: C:\Users\asgal\Documents\Projects\litgame\single_player_app\assets\images\
  icons_background_color: transparent
  architecture: x86
  capabilities: 'internetClient'
  languages: ru-ru
  store: true